version: 2.1

executors:
  node:
    docker:
      - image: circleci/node
    working_directory: ~/project/portfolio

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn
      - save_cache:
          paths:
            - node_modules/
          key: v1-portfolio-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - portfolio

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test

  deploy:
    executor: node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e5:34:75:2d:26:c2:2d:05:70:29:67:86:fa:c3:22:17"
      - run:
          name: Setting git user and pass
          command: |
            git config --global user.name CircleCI
            git config --global user.email circleci@opendata.team
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Github Pages
          command: yarn deploy

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
