version: 2.1

executors:
  node:
    docker:
      - image: circleci/node
    working_directory: ~/project/portfolio

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn
      - save_cache:
          paths:
            - node_modules/
          key: v1-portfolio-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - portfolio

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test

  deploy:
    executor: node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:1f:e5:69:ef:e1:ed:30:66:38:03:d4:8a:d9:66:43"
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Github Pages
          command: yarn deploy StrictHostKeyChecking=no

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
