version: 2.1

executors:
  node:
    docker:
      - image: circleci/node
    working_directory: ~/project/portfolio

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn
      - save_cache:
          paths:
            - node_modules/
          key: v1-portfolio-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - portfolio

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test

workflows:
  version: 2
  install-and-test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - build
